# VDBFUSION
#voxel_size: 0.005
voxel_size: 0.01
#sdf_trunc: 0.15
sdf_trunc: 0.07
space_carving: True

# Triangle Mesh Generation
fill_holes: True
min_weight: 3.0

# PointCloud
apply_pose: True
preprocess: True
min_range: 0.25 # 1.0
max_range: 10.0
pcl_topic: "/rs_camera_1/voxel_grid/output"
#pcl_topic: "/rs_camera_1/outlier_removal/output"

# Transform
use_tf_transforms: true
parent_frame: "pcl_crop_box_1"
child_frame: "rs_camera_1_color_optical_frame"
timestamp_tolerance_ns: 1000
